### ISSUE TITLE
Video Format

### ISSUE THREAD

**Issue by zerolfc** [burt202/lite-uploader#10]
Does it support video format?
it return empty  when i print_r($_FILES)

**Comment by burt202** [comment]
Hi, Ive just tested the uploader with video file types and it works fine. This plugin is just a generic file upload tool, it does not care what file types you upload (unless you add validation). What file type are you trying to upload? Can you copy in your JS/PHP code, I dont mind having a little debug?

**Comment by zerolfc** [comment]
Sorry, its fine now. i forgot to extend the max upload on the server side :)
