### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by zerolfc** [burt202/lite-uploader#11]
Is there any compatibility issue with Internet Explorer?

i was testing it in IE11, it doesn't give me any warning or error at all.

It works great on any other browsers though!

```javascript
$('#uploader').liteUploader({
 script: 'dialog/',
 rules: {
   maxSize: 31457280
  },
   params: { form: 'upload', file_type: 'video' }
})
.on('lu:errors', function (e, errors) {
   var is_error = false;
   $.each(errors, function (i, error) {
     if (error.errors.length > 0) {
         alert('Maximum 30MB video') // No alert in Internet Explorer
     }
    });
})
.on('lu:success', function (e, errors) {
   $('#uploader').liteUploader().off();
});
```

Please note: it does sometimes works. the first click, browse dialog open but wont upload, but then second click then it works.

**Comment by burt202** [comment]
My IE debugging facilities arent great currently, let me get back to you on this one. In the meantime if you find anything let me know

**Comment by burt202** [comment]
Sorry ive taken a while to get back to you on this. See the source at the following link

http://test.burtdev.net/lite-uploader/examples/issue11.html

The code is based on your example. I loaded it up in IE11, tried uploading .mp4, .avi and .mpg greater than 40mb in size and I could see the alert. Are you still having problems with this?

**Comment by zerolfc** [comment]
sorry.. it was working fine already..

there was nothing wrong with the library.

it was my server upload limitation -- so i increased the upload limit then it worked fine 

thanks :)

**Comment by burt202** [comment]
OK. But after looking into how the errors were being triggered, I have made some tidups to the plugin in that area. Expect v2.2.0 to be pushed in the next day or so
