### ISSUE TITLE
CSS Theme?

### ISSUE THREAD

**Issue by Puntella** [burt202/lite-uploader#12]
Hi friend,

Excellent repo! I don't know why, but is the only one that work on my hosting.

How can I format a progress bar?
I don't understand why the example gave me different lines to the upload progress.

Best regards,

**Comment by burt202** [comment]
Hi, thanks for the feedback. The plugin is purely JavaScript so it does not care, or have any effect on the CSS (or theme) that is used around it. If you want good examples on how to style progress bars, see https://css-tricks.com/css3-progress-bars/ and use the progress event from the plugin to update its progress size. I hope this helps. If you have any specific questions about the plugin let me know. I'll close this issue, and assume your happy if i dont here anything within a couple days. Cheers
