### ISSUE TITLE
add method to set all params using $("form").serialize()

### ISSUE THREAD

**Issue by leeoniya** [burt202/lite-uploader#13]
...possibly ignoring all file inputs. pretty please?

**Comment by burt202** [comment]
Hi, thanks for getting in touch. So Im not sure if Id like to put something like $("form").serialize() within the plugin itself, but what I could do is change the public addParam function to take an object of values rather than just a string. Thoughts?

**Comment by leeoniya** [comment]
right, I did not mean to use `$("form").serialize()`, internally. I just want to be able to set all params at once using the output of `.serialize()` which is a query string like `single=Single&multiple=Multiple&multiple=Multiple3&check=check2&radio=radio1&arr[]=1&arr[]=2`, or `.serializeArray()`, or `jQuery.param()`;

what i'm suggesting is to also allow the `params` option to accept the return value of those functions directly, otherwise you have to write restructuring loops outside of the plugin.

https://github.com/burt202/lite-uploader/blob/master/jquery.liteuploader.js#L142

```js
if (typeof this.params == "string") {
    var params = {};

    this.params.split("&").forEach(function(kvPair) {
         // ....
        params[key] = value;
    });
}
else {
    var params = this.params;
}

$.each(params, function (key, value) {
    formData.append(key, value);
});
```

**Comment by burt202** [comment]
Im not too keen on loosening the API so that params could either be a string, array or object. The main aim of the plugin was for it to be as "lite" as possible (hence the name) so Id rather the logic you mentioned lived outside of it, so the params var remains consistent. In this instance, I think the params remaining an object internally makes the most sense and makes it easier to reason with. With all this said, Im up for adding/changing the public methods available so it makes manipulating the params easier after instantiation. Sorry for my stubborness, but still up for hearing your further thoughts. Cheers

**Comment by leeoniya** [comment]
> Sorry for my stubborness, but still up for hearing your further thoughts.

No need to apologize. Maybe the situation isn't as bad as I imagine, would the following work?:

```js
var params = {};

$(this).serializeArray().forEach(function(p) {
    params[p.name] = p.value;
});

// now just pass params to uploader?
```

**Comment by burt202** [comment]
Looks good to me: https://jsfiddle.net/1kgj6jsz/

As long as you pass it an object it will be fine. So youre not interested in supplying params after instantiation then?

**Comment by leeoniya** [comment]
no, i'm just handling a semantic html5 `<form>` submit that i want to XHR2-ify with upload progress. the form has additional inputs that need to be submitted along with the files. i'll just intercept the submit event and proxy all the form data to `lite-uploader`. the less code to to this, the better :)

**Comment by burt202** [comment]
Can this issue be closed now? Just looking at your scenario again, you could probably clean up your code by using Array.reduce (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) if you havent already

**Comment by leeoniya** [comment]
i haven't integrated this plugin yet, but i'll re-open if things don't work. thanks!
