### ISSUE TITLE
Simple support for drag and drop and paste uploads.

### ISSUE THREAD

**Issue by Zmetser** [burt202/lite-uploader#19]
Pre v2.3.0 it was easy enough to implement a past or drag'n drop upload. It was just another listener in the `_init` call.
But now with the `_init` gone and the `getFiles` and `trigger` passed to the `LiteUploader` I'm not sure how to approach this.

@burt202  Any advice how to proceed on this, to fit your architecture?

**Comment by burt202** [comment]
Basic support for drag/drop will come in v3.2.0, which will be pushed soon

**Comment by burt202** [comment]
v3.2.0 has been pushed/published. See example here for basic drag/drop example https://github.com/burt202/lite-uploader/blob/master/examples.md#passing-a-filelist-in-as-a-parameter. Hope this helps

**Comment by Zmetser** [comment]
That is a nice pattern, and solves my last issue with liteuploader.
Thank you for your support!
