### ISSUE TITLE
Error: ".done is not a function" from returned Promise.resolve(formData)

### ISSUE THREAD

**Issue by keenlinks** [burt202/lite-uploader#23]
The Promise object does not have a done(), but rather a then(). Replacing done() with then() resolves the issue.

Just a note, it seems the JS Promise is not supported in IE11 (and IE11 still has big usage), maybe consider returning to the jQuery promise methods.

Either way, wonderful library. I will continue to use.

Thanks,
Scott (keenlinks)

**Comment by burt202** [comment]
Yeh nice spot. I forgot to update some unit tests which would have caught this. I'll push a fix later.

In regard to IE11 support, this plugin was originally created to only support the latest and greatest, that was 3 years ago though, and most modern browsers have caught up now. That said, I do want to start being less reliant on some of the jquery methods and use native where I can, and where I deem support is high enough. This was true for the Promise object.

I guess if people want IE11 support then they can just stay at 3.3.0. The plugin is pretty stable now, and not a lot will change on 3.x. If version 4 ever comes along, it'll probably be even more IE unfriendly.

Hope this helps (and you agree)

Cheers

**Comment by keenlinks** [comment]
Not a problem. Despite my suggestion, I do agree with moving ahead. Also, if it keeps you interested in developing this module then that is a good thing. Once again, great module, I love the ease of integration.
