### ISSUE TITLE
image height width validation

### ISSUE THREAD

**Issue by klausgao** [burt202/lite-uploader#24]
a good package man!
it is better we have height and width validation for image.

**Comment by burt202** [comment]
Hi, thanks for the suggestion. I'll see what I can do. No guarantees!

**Comment by burt202** [comment]
Sorry for the delay but just to give you an update on this. I wont be putting in height and width validation directly into the plugin as the plugin is for uploading any types of file, and height and width only relate to some file types. I will, however, look into adding a way of adding custom validators so you can achieve this yourself, outside the plugin, will minimal effort. I aim to do this as part of v4 in the next week or so. Hope this helps

**Comment by burt202** [comment]
I've added an option to add custom validators, see [https://github.com/burt202/lite-uploader/blob/master/examples.md#custom-validators](https://github.com/burt202/lite-uploader/blob/master/examples.md#custom-validators) for an example. I'll close this once v4 is released. Cheers

**Comment by klausgao** [comment]
thx man 😄😄



可用于iOS的myMail发送


2016年7月13日 星期三 +0800 06:13 发件人 barry205  <notifications@github.com>:

**Comment by burt202** [comment]
v4 now released
