### ISSUE TITLE
Response status 400-500 is not reported as an error

### ISSUE THREAD

**Issue by AntonBaukin** [burt202/lite-uploader#26]
When server returns status code of an error (such as 404, 500), it is not reported fir the failure callback. Regretfully, we can't postpone the progress events as server returns the status when the uploading is fully complete (the progress is 100)
[status-handling.patch.zip](https://github.com/burt202/lite-uploader/files/357084/status-handling.patch.zip)
.

**Comment by burt202** [comment]
This has been addressed and will be part of the next release. Please bear in mind that the most recent code in which you patched above is still a work in progress so it will be a little rough around the edges. Im not far off publishing v4 though. I'll close this once it is released. Cheers

**Comment by burt202** [comment]
v4 now released
