### ISSUE TITLE
Sequencial upload with singleFileUploads

### ISSUE THREAD

**Issue by AntonBaukin** [burt202/lite-uploader#27]
When singleFileUploads mode is used, as it's desired, each multi-part request has only one payload. But the requests are done in parallel without any limit (queueing)! Considering the progress, you can't tell easily on what file the progress is reported. I've extepcted that this mode sends file one-by-one.

**Comment by AntonBaukin** [comment]
The implementation may be easy enough: 

     _startUpload: function (files) {
      var self = this, index = 0, uploads = this._splitFiles(files);

      function next()
      {
        if (index >= uploads.length) return

        var xhr = self._buildXhrObject();
        xhr.addEventListener('load', next);

        return self._beforeRequest(uploads[index++]).then(
          function (formData) {
            return xhr.send(formData);
          })
       }

       return next();
    }

**Comment by burt202** [comment]
Hi, yeh Im tempted to agree with you here. Youre implementation is pretty much there. If you wanted to create a PR for this WITH TESTS, then ill be happy to merge. Otherwise, itll join the queue of stuff to do. Im currently preparing v4 which hopefully will be out soon. This could be a part of that release

**Comment by AntonBaukin** [comment]
Regretfully, this error is considerable. When this option is not set, and user selects 100 files, browser sends them in single huge request, and server handles them while reading the stream. But when this option is set on, 100 files generate 100 simultaneous requests, thus overloading the server...

**Comment by burt202** [comment]
@Zmetser wanted this originally, and it was introduced via his PR. I would like to hear his thoughts. Series or parallel?

**Comment by sp90** [comment]
and how to detect on progress which image has what progress

**Comment by Zmetser** [comment]
If I understand the problem correctly, I'd just let the browser handle the "simultaneous" requests. Even if the user initiates 100 uploads, the browser won't start all the 100 concurrent requests to the same domain, but starts a couple and add the rest to the pending queue, so serialisation of paralell requests are handled by the browser.

This is the most recent article I was able to find in the topic: [Maximum concurrent connections to the same domain for browsers
](http://sgdev-blog.blogspot.hu/2014/01/maximum-concurrent-connection-to-same.html)
Here's a quick test: http://jsbin.com/copakeceta/edit?js,output (open network tab)

**Comment by Zmetser** [comment]
@sp90: My take on how to track individual upload progresses: https://github.com/burt202/lite-uploader/pull/29

Adds the file as an argument to the `lu:progress` event.

**Comment by burt202** [comment]
This issue has now been addressed with thanks to @Zmetser 
See [this example](https://github.com/burt202/lite-uploader/blob/master/examples.md#mutilple-progress) for more.

This change will be part of the next release which will be v5.0.0 because of the breaking change in the progress event call signature. I hope this helps

**Comment by burt202** [comment]
v5.0.0 is now published. Thanks all for help and suggestions
