### ISSUE TITLE
Node App Error

### ISSUE THREAD

**Issue by kbala** [burt202/lite-uploader#31]
I tried the 'node without jquery' example.

```
var LiteUploader = require("lite-uploader");

var options = {script: "test.php"};  // takes all of the documented options
var getFiles = function () {
  // return a FileList
};
var onEvent = function (name, value) {
  // called on all documented events
};

var liteUploader = new LiteUploader(options, getFiles, onEvent)
```

It throws error like,  `TypeError: LiteUploader is not a constructor`

@burt202  Any idea?

**Comment by burt202** [comment]
I'll have a look at this later

**Comment by burt202** [comment]
I cant seem to reproduce the issue you're getting. What version are you using?

**Comment by kbala** [comment]
node 8.4.0

**Comment by burt202** [comment]
And what version of lite uploader?

**Comment by kbala** [comment]
I was using 5.0.2.

**Comment by kbala** [comment]
Also, seems like the node version of lite-uploader doesn't support `progress` event?

**Comment by kbala** [comment]
One thing I forgot to tell. i.e. I am using this `lite-uploader` in a `electron` app where I got the above error.

**Comment by burt202** [comment]
OK. Thanks for the info. Can you send me the smallest example possible that re-creates the issue, so I can take a look?

**Comment by burt202** [comment]
Closing as issue is over a month old without reply
