### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by zerolfc** [burt202/lite-uploader#32]
I ve got this error when using webpack to compile the scripts.

```
jQuery.Deferred exception: $(...).liteUploader is not a function TypeError: $(...).liteUploader is not a function
```
i am using Laravel mix `autoload` to load `$` jquery as global variable, settings. Any idea?
`https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md`

Adding the UMD module support code, fixed the problem.

```
if (typeof define === 'function' && define.amd) {
  define(['jquery'], factory);
}

**Comment by burt202** [comment]
Can you submit a PR?

**Comment by zerolfc** [comment]
ok will do :)
