### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by davidmind** [burt202/lite-uploader#36]
Hi, @burt202 am a graphics designer. I will like to know if you want me to create a logo for your project.

**Comment by davidmind** [comment]
@burt202 are you there?

**Comment by davidmind** [comment]
@burt202 are you there?

**Comment by burt202** [comment]
Hi David, You can create a logo if you want but I really dont think this small project merits it. Up to you

**Comment by davidmind** [comment]
Ok, I will work  on a logo for these project. If you have bigger project also I will create a logo also for it

**Comment by davidmind** [comment]
Hi @burt202 sorry it is coming late I have been trying different elements combination, most of it seems not to work as I expect. But this is what I came up with. I made the logo denote a light weight uploading server. 
![light-upload-prep.png](https://cdn.steemitimages.com/DQmaq5JQi53ZJzvDHdbrBSFvTWVzUhGJ1CxFMjac1qsGkok/light-upload-prep.png)

**Comment by davidmind** [comment]
@burt202 are you there?
